# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: kwigo-mongo
    # restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: kwigo-mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  node:
    image: bitnami/node
    container_name: kwigo-backend
    command: "sh -c 'apt-get update && apt-get install -y build-essential && apt-get install -y python && npm install && node index.js'"
    volumes:
      - ./:/app
    ports:
      - 4000:4000

  duckdns:
     image: linuxserver/duckdns
     container_name: duckdns
     environment:
       - TZ=Europe/Rome
       - SUBDOMAINS=camus
       - TOKEN=***REMOVED***
     # restart: always
